# Generated by Django 2.0.9 on 2025-08-28 09:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.CharField(max_length=100)),
                ('feedback_date', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='order_sub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orders', models.CharField(max_length=100)),
                ('payment_status', models.CharField(max_length=100)),
                ('payment_date', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('quantity', models.CharField(max_length=100)),
                ('CATEGORY', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.category')),
            ],
        ),
        migrations.CreateModel(
            name='review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(max_length=100)),
                ('review_date', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='seller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('profile_image', models.CharField(max_length=100)),
                ('bio', models.CharField(max_length=500)),
                ('address', models.CharField(max_length=200)),
                ('place', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=100)),
                ('post', models.CharField(max_length=100)),
                ('latitude', models.CharField(max_length=100)),
                ('longitude', models.CharField(max_length=100)),
                ('proof', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('profile_image', models.CharField(max_length=100)),
                ('bio', models.CharField(max_length=500)),
                ('address', models.CharField(max_length=200)),
                ('place', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=100)),
                ('post', models.CharField(max_length=100)),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='seller',
            name='LOGIN',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='review',
            name='USER',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.user'),
        ),
        migrations.AddField(
            model_name='product',
            name='SELLER',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.seller'),
        ),
        migrations.AddField(
            model_name='orders',
            name='SELLER',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.seller'),
        ),
        migrations.AddField(
            model_name='orders',
            name='USER',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.user'),
        ),
        migrations.AddField(
            model_name='order_sub',
            name='ORDER',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.orders'),
        ),
        migrations.AddField(
            model_name='order_sub',
            name='PRODUCT',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.product'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='USER',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.user'),
        ),
        migrations.AddField(
            model_name='cart',
            name='ORDER',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.orders'),
        ),
        migrations.AddField(
            model_name='cart',
            name='PRODUCT',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.product'),
        ),
    ]
