# Generated by Django 3.0 on 2026-01-04 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_type',
            field=models.CharField(default='online', max_length=100),
        ),
    ]
