# Generated by Django 3.2.25 on 2025-09-01 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='rating',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
