# Generated by Django 3.0 on 2026-01-04 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_order_order_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_type',
        ),
    ]
