# Generated by Django 3.2.25 on 2025-09-01 09:56

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('my_app', '0002_review_rating'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='seller',
            new_name='distributor',
        ),
    ]
