# Generated by Django 3.2.25 on 2025-09-01 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_rename_seller_distributor'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributor',
            name='status',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
