# Generated by Django 3.2.4 on 2026-01-05 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_remove_order_order_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_type',
            field=models.CharField(default='online', max_length=100),
        ),
    ]
