# Generated by Django 3.2.4 on 2026-01-05 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_order_order_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_sub',
            name='price',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
