# Generated by Django 3.2.25 on 2025-09-01 10:49

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('my_app', '0004_distributor_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user',
            new_name='seller',
        ),
    ]
