# Generated by Django 3.2.25 on 2025-09-26 07:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('my_app', '0005_rename_user_seller'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='seller',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='SELLER',
            new_name='CUSTOMER',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='SELLER',
            new_name='CUSTOMER',
        ),
    ]
