# Generated by Django 3.2.4 on 2026-01-05 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_order_sub_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_sub',
            name='quantity',
            field=models.IntegerField(max_length=100),
        ),
    ]
