# Generated by Django 2.2.18 on 2025-11-04 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0006_auto_20250926_1251'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='review',
            new_name='reviews',
        ),
    ]
