# Generated by Django 2.2.18 on 2025-11-06 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0007_auto_20251104_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='DISTRIBUTOR',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='my_app.distributor'),
        ),
    ]
