# Generated by Django 3.2.4 on 2026-02-01 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0008_auto_20260113_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_sub',
            name='price',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='stock',
            name='price',
            field=models.CharField(max_length=7),
        ),
    ]
