# Generated by Django 2.2.18 on 2025-11-06 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0008_review_distributor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='feedback',
            new_name='feedbacks',
        ),
    ]
