# Generated by Django 2.2.18 on 2025-11-06 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0009_auto_20251106_1119'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='CUSTOMER',
            new_name='DISTRIBUTOR',
        ),
        migrations.AddField(
            model_name='feedback',
            name='DISTRIBUTOR',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='my_app.distributor'),
        ),
    ]
