# Generated by Django 3.2.4 on 2026-02-08 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0009_auto_20260201_1432'),
    ]

    operations = [
        migrations.CreateModel(
            name='recently_viewed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_date', models.DateTimeField(auto_now=True)),
                ('STOCK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.stock')),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.customer')),
            ],
        ),
    ]
