# Generated by Django 2.2.18 on 2025-11-06 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0010_auto_20251106_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='USER',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='my_app.customer'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='feedback_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='feedbacks',
            field=models.TextField(),
        ),
        migrations.AddConstraint(
            model_name='feedback',
            constraint=models.CheckConstraint(check=models.Q(('USER__isnull', False), ('DISTRIBUTOR__isnull', False), _connector='OR'), name='feedback_has_actor'),
        ),
    ]
