# Generated by Django 2.2.18 on 2025-11-08 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0011_auto_20251106_1140'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='feedback',
            name='feedback_has_actor',
        ),
        migrations.AddField(
            model_name='feedback',
            name='type',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feedback',
            name='DISTRIBUTOR',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='my_app.distributor'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='USER',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='my_app.customer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feedback',
            name='feedback_date',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='feedbacks',
            field=models.CharField(max_length=100),
        ),
    ]
