# Generated by Django 2.2.18 on 2025-11-08 14:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0012_auto_20251108_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='DISTRIBUTOR',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='my_app.distributor'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='USER',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='my_app.customer'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='feedback_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='feedbacks',
            field=models.TextField(),
        ),
    ]
