# Generated by Django 2.2.18 on 2025-11-08 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0013_auto_20251108_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='USER',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='my_app.customer'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='review',
            name='reviews',
            field=models.TextField(),
        ),
    ]
