# Generated by Django 2.2.18 on 2025-11-09 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0014_auto_20251108_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='feedback_date',
            field=models.CharField(max_length=100),
        ),
    ]
