# Generated by Django 2.2.18 on 2025-11-17 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0016_auto_20251117_0923'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_sub',
            name='STOCK',
        ),
        migrations.DeleteModel(
            name='stock',
        ),
    ]
