# Generated by Django 2.2.18 on 2025-11-17 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0017_auto_20251117_0929'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='CUSTOMER',
            new_name='DISTRIBUTOR',
        ),
    ]
