# Generated by Django 2.2.18 on 2025-11-17 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0019_auto_20251117_0943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='DISTRIBUTOR',
        ),
    ]
