# Generated by Django 2.2.18 on 2025-11-21 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0020_remove_product_distributor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AddField(
            model_name='stock',
            name='price',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
