# Generated by Django 2.2.18 on 2025-12-01 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0022_auto_20251201_0925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_sub',
            name='PRODUCT',
        ),
        migrations.AddField(
            model_name='order',
            name='amount',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
