# Generated by Django 2.2.18 on 2025-12-01 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0023_auto_20251201_0945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='orders',
        ),
    ]
