# Generated by Django 2.2.18 on 2025-12-01 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0024_remove_order_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='PAYMENT',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='my_app.payment'),
            preserve_default=False,
        ),
    ]
