# Generated by Django 2.2.18 on 2025-12-01 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0025_order_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='PAYMENT',
        ),
    ]
