# Generated by Django 2.2.18 on 2025-12-15 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0026_remove_order_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='PRODUCT',
        ),
        migrations.AddField(
            model_name='cart',
            name='STOCK',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='my_app.stock'),
            preserve_default=False,
        ),
    ]
