# Generated by Django 2.2.18 on 2025-12-22 04:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0028_wishlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='ORDER',
        ),
        migrations.AddField(
            model_name='cart',
            name='USER',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='my_app.customer'),
            preserve_default=False,
        ),
    ]
