# Generated by Django 2.2.18 on 2025-12-23 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0030_auto_20251223_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='customer',
            name='bio',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='customer',
            name='profile_image',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='distributor',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='distributor',
            name='bio',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='distributor',
            name='profile_image',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='distributor',
            name='proof',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.TextField(),
        ),
    ]
