# Generated by Django 2.2.18 on 2025-12-27 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0031_auto_20251223_1429'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistributorCustomerLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('CUSTOMER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.customer')),
                ('DISTRIBUTOR', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.distributor')),
            ],
        ),
    ]
